//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_Spanish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_Spanish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Localization.AppResources.Spanish", typeof(AppResources_Spanish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        public static string AlertDialogLabel {
            get {
                return ResourceManager.GetString("AlertDialogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientación actual.
        /// </summary>
        public static string CurrentOrientationLabel {
            get {
                return ResourceManager.GetString("CurrentOrientationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluación de desarrollo.
        /// </summary>
        public static string DevAssessmentLabel {
            get {
                return ResourceManager.GetString("DevAssessmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientación del dispositivo.
        /// </summary>
        public static string DeviceOrientationPageTitle {
            get {
                return ResourceManager.GetString("DeviceOrientationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string DialogCloseButtonLabel {
            get {
                return ResourceManager.GetString("DialogCloseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pantalla de diálogo.
        /// </summary>
        public static string DialogDisplayPageTitle {
            get {
                return ResourceManager.GetString("DialogDisplayPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar diálogo de alerta.
        /// </summary>
        public static string DisplayAlertDialogButtonLabel {
            get {
                return ResourceManager.GetString("DisplayAlertDialogButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar diálogo de error.
        /// </summary>
        public static string DisplayErrorDialogButtonLabel {
            get {
                return ResourceManager.GetString("DisplayErrorDialogButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese texto para hablar.
        /// </summary>
        public static string EnterTextToSpeakLabel {
            get {
                return ResourceManager.GetString("EnterTextToSpeakLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vagar.
        /// </summary>
        public static string ErrorDialogLabel {
            get {
                return ResourceManager.GetString("ErrorDialogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtener orientación.
        /// </summary>
        public static string GetOrientationButtonLabel {
            get {
                return ResourceManager.GetString("GetOrientationButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casa.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paisaje.
        /// </summary>
        public static string LandscapeOrientationLabel {
            get {
                return ResourceManager.GetString("LandscapeOrientationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto Recogedor.
        /// </summary>
        public static string PhotoPickerPageTitle {
            get {
                return ResourceManager.GetString("PhotoPickerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoger.
        /// </summary>
        public static string PickPhotoButtonLabel {
            get {
                return ResourceManager.GetString("PickPhotoButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige una foto.
        /// </summary>
        public static string PickPhotoLabel {
            get {
                return ResourceManager.GetString("PickPhotoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrato.
        /// </summary>
        public static string PortraitOrientationLabel {
            get {
                return ResourceManager.GetString("PortraitOrientationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una alerta para mostrar.
        /// </summary>
        public static string SelectAlertToDisplayLabel {
            get {
                return ResourceManager.GetString("SelectAlertToDisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hablar.
        /// </summary>
        public static string SpeakButtonLabel {
            get {
                return ResourceManager.GetString("SpeakButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto a voz.
        /// </summary>
        public static string TextToSpeechPageTitle {
            get {
                return ResourceManager.GetString("TextToSpeechPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indefinido.
        /// </summary>
        public static string UndefinedOrientationLabel {
            get {
                return ResourceManager.GetString("UndefinedOrientationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido A Evaluación de desarrollo.
        /// </summary>
        public static string WelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomeLabel", resourceCulture);
            }
        }
    }
}
